import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AIOps Assistant",
  description: "Generated by create next app",
  icons: {
    // icon: "/favicon.svg", // Or use .svg or .png
    icon: "/aislogo.png", // Or use .svg or .png

  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Improved Header */}
        <header className="bg-gradient-to-r from-blue-600 to-indigo-700 shadow-lg">
          <div className="px-6 py-4">
            <div className="flex items-center space-x-4">
              {/* Logo */}
              <div className="flex-shrink-0">
                <Image 
                  src="/open-cluster-management.png" 
                  alt="Open Cluster Management Logo" 
                  width={48} 
                  height={48}
                  className="rounded-lg"
                />
              </div>
              {/* Title */}
              <div>
                <h1 className="text-2xl font-bold text-white">Open Cluster Management</h1>
                <p className="text-blue-100 text-sm">AI-Powered Operations Assistant</p>
              </div>
            </div>
          </div>
        </header>
        
        {children}
      </body>
    </html>
  );
}
