import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ACM Chat Agent",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg", // Or use .svg or .png
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-8 bg-white flex items-center justify-between">
          {/* Left side: logo + title */}
          <div className="flex items-center">
              <div className="flex items-center mr-4">
                  <Image 
                      src="/RedHat.svg" 
                      alt="Red Hat Logo" 
                      width={180} 
                      height={60}
                  />
              </div>
              <h1 className="text-2xl font-light text-gray-200">Advanced Cluster Management</h1>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
